project_id = "ckcuebcrsuhthoslgcrn"

[functions.auto-resume-memberships]
verify_jwt = false

[functions.schedule-notifications]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.emergency-freeze]
verify_jwt = false

[functions.emergency-resume]
verify_jwt = false
